kind: Secret
apiVersion: v1
metadata:
  name: caikit-embeddings-cos
data:
  access-key: {{ .Values.secrets.cosAccessKey | b64enc }}
  secret-key: {{ .Values.secrets.cosSecretKey | b64enc }}
type: ibm/ibmc-s3fs